### ISSUE TITLE
Callback event when node/link is deleted

### ISSUE THREAD

**Issue by Chandra-Lavanya** [tokarchyn/react-easy-diagram#17]
Is there any event that gets triggered when a node/link is deleted?

**Comment by tokarchyn** [comment]
Hi @Chandra-Lavanya, not right now (I will try to add new callbacks this week), but since we use MobX for state management you can use [reaction](https://mobx.js.org/reactions.html#reaction) function like this:
``` js
      reaction(
        () => {
            // When you read properties in any observable object mobx subscribes to changes in this properties
            // and will call function you provide as a second argument to reaction function.
            return Array.from(storeRef.current.linksStore.links.keys());
        },
        (currentLinkIds, prevLinkIds) => {
          if ((currentLinkIds?.length ?? 0) < (prevLinkIds?.length ?? 0)) {
            // links were removed
          }
        }
      )
```

See also another [example](https://tokarchyn.github.io/react-easy-diagram/examples/callbacks/) were `reaction` is used.

**Comment by Chandra-Lavanya** [comment]
Can i know, when will the changes be available??

**Comment by tokarchyn** [comment]
@Chandra-Lavanya New version `0.10.0` has been published. Thank you for your patience.

**Comment by Chandra-Lavanya** [comment]
Thanks @tokarchyn
